### PR TITLE
disable cloning submodules

### PR DESCRIPTION
**Pull request by ab77**
See, https://github.com/renovatebot/renovate/discussions/27280#discussioncomment-8711418

### CODE REVIEW

**Review by klutchell — COMMENTED** [review]
How long has this feature been enabled? Hopefully there are no post upgrade tasks that rely on submobules being cloned? Seems unlikely and they can be enabled at a repo level I guess?

**Comment by ab77** [comment]
> How long has this feature been enabled? Hopefully there are no post upgrade tasks that rely on submobules being cloned? Seems unlikely and they can be enabled at a repo level I guess?

[since](https://github.com/balena-io/renovate-config/commit/44a9cd1d0769ebd256afb99d35c32a496475ebc8)

**Review by klutchell — APPROVED** [review]
If this breaks any repositories we can enable cloning of (public) submodules at the repo level config.

**Comment by ab77** [comment]
> If this breaks any repositories we can enable cloning of (public) submodules at the repo level config.

Perfect. Also:

```
2024-03-07T22:40:49.5735641Z DEBUG: branches info extended (repository=balena-io/environment-playground)
2024-03-07T22:40:49.5736607Z        "branchesInformation": [
2024-03-07T22:40:49.5737127Z          {
2024-03-07T22:40:49.5737712Z            "branchName": "renovate/base-digest",
2024-03-07T22:40:49.5738353Z            "prNo": null,
2024-03-07T22:40:49.5738925Z            "prTitle": "Update base digest to 2ff2567",
2024-03-07T22:40:49.5739674Z            "result": "no-work",
2024-03-07T22:40:49.5740227Z            "upgrades": [
2024-03-07T22:40:49.5740701Z              {
2024-03-07T22:40:49.5741238Z                "datasource": "git-refs",
2024-03-07T22:40:49.5741853Z                "depName": "base",
2024-03-07T22:40:49.5742427Z                "displayPending": "",
2024-03-07T22:40:49.5743095Z                "currentValue": "master",
2024-03-07T22:40:49.5743699Z                "newValue": "master",
2024-03-07T22:40:49.5744305Z                "packageFile": ".gitmodules",
2024-03-07T22:40:49.5744932Z                "updateType": "digest",
2024-03-07T22:40:49.5745897Z                "packageName": "https://github.com/balena-io/environments-base.git"
2024-03-07T22:40:49.5747083Z              }
2024-03-07T22:40:49.5747507Z            ]
2024-03-07T22:40:49.5747898Z          },
```

**Pull request merged**
